{% set name = "pdivas" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdivas-{{ version }}.tar.gz
  sha256: 66ac22aab5a6cf839ab1fffe406ee3381f41f36d97932486c152f4e064d9cd7a

build:
  entry_points:
    - pdivas=pdivas.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas >=1.3
    - numpy >=1.21
    - cyvcf2 >=0.11
    - scikit-learn =1.0.2

test:
  imports:
    - pdivas
  commands:
    - pip check
    - pdivas --help
  requires:
    - pip

about:
  home: http://github.com/account/repository
  summary: 'PDIVAS: Pathogenicity predictor of Deep-Intronic Variants causing Aberrant Splicing'
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
